import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: '#1f1f1f',
  },
  profileText: {
    color: '#ffffff',
    margin: 15,
    fontSize: 18,
    fontWeight: 600,
  },
  headerText: {
    margin: 15,
    fontSize: 28,
    fontWeight: 600,
    color: '#ffffff',
    alignSelf: 'center',
  },
  text: {
    color: '#ffffff',
    margin: 15,
    fontSize: 24,
    fontWeight: 600,
  },
  box: {
    backgroundColor: 'transparent',
    margin: 5,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ffffff',
    alignItems: 'center',
  },
  draftMessagesBox: {
    backgroundColor: '#1f1f1f',
    margin: 5,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ffffff',
    alignItems: 'center',
  },
  title: {
    color: '#ffffff',
  },
  addContact: {
    marginHorizontal: 5,
    marginTop: 5,
    height: 55,
    width: undefined,
    aspectRatio: 1,
    alignSelf: 'center',
    backgroundColor: 'gray',
    borderRadius: 10,
  },
  addContactBtn: {
    fontSize: 28,
    borderRadius: 5,
    alignSelf: 'flex-end',
    marginTop: 10,
    marginHorizontal: 10,
    marginBottom: 10,
    borderColor: '#000000',
    width: 50,
  },
  contactSearch: {
    width: 270,
    height: 50,
    marginRight: 20,
    color: '#ffffff',
    textAlign: 'center',
    fontSize: 24,
    placeholderTextColor: '#ffffff',
    backgroundColor: 'gray',
    borderRadius: 10,
  },
  contactOptions: {
    height: 50,
    width: undefined,
    aspectRatio: 0.2,
    alignSelf: 'center',
  },
  optionsPanelContacts: {
    position: 'absolute',
    backgroundColor: 'gray',
    height: 120,
    width: 200,
    right: 0, // -210,
    top: 140,
    borderBottomLeftRadius: 20,
    borderTopLeftRadius: 20,
  },
  header: {
    flex: 1,
    backgroundColor: '#2A2F4F',
  },
  profileTextInput: {
    color: '#ffffff',
    margin: 15,
    fontSize: 18,
    fontWeight: 500,
    placeholderTextColor: '#ffffff',
    backgroundColor: 'gray',
    paddingLeft: 20,
    borderRadius: 10,
  },
  signupTextInput: {
    color: '#ffffff',
    margin: 15,
    fontSize: 24,
    fontWeight: 500,
    placeholderTextColor: '#ffffff',
    backgroundColor: 'gray',
    paddingLeft: 20,
    borderRadius: 10,
  },
  activityIndicator: {
    top: '40%',
    alignSelf: 'center',
  },
  activityIndicatorView: {
    padding: 5,
    flex: 10,
  },
  view: {
    padding: 0,
    flex: 1,
  },
  tabText: {
    marginTop: 20,
    color: '#000000',
    margin: 15,
    fontSize: 18,
    fontWeight: 500,
  },
  newChatButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ffffff',
    height: 60,
    width: 120,
    backgroundColor: '#838485',
  },
  newChatButtonText: {
    color: '#ffffff',
    margin: 15,
    fontSize: 18,
    fontWeight: 600,
  },
  chatsChatView: {
    flex: 1,
    flexDirection: 'column',
    borderColor: '#ffffff',
    borderWidth: 2,
    margin: 2,
  },
  chatsChatName: {
    color: '#ffffff',
    flex: 7,
    marginTop: 10,
    marginLeft: 10,
    fontSize: 25,
    alignItems: 'center',
    fontWeight: 600,
    width: '90%',
  },
  chatsLastMessage: {
    color: '#ffffff',
    margin: 15,
    flex: 7,
    marginTop: 2,
    marginLeft: 10,
    fontSize: 22,
    alignSelf: 'flex-start',
    fontWeight: 450,
  },
  chatsTimestamp: {
    color: '#ffffff',
    margin: 15,
    flex: 7,
    marginTop: 2,
    marginLeft: 10,
    fontSize: 15,
    alignSelf: 'flex-end',
  },
  chatsNewChatModal: {
    position: 'absolute',
    backgroundColor: '#1f1f1f',
    borderBottomLeftRadius: 20,
    borderTopLeftRadius: 20,
    height: 200,
    width: '80%',
    top: 200,
    right: '10%',
    borderRadius: 15,
    margin: 10,
  },
  chatsNewChatTextInput: {
    margin: 15,
    fontWeight: 500,
    fontSize: 22,
    color: '#ffffff',
    alignSelf: 'center',
    placeholderTextColor: '#d1d9e0',
    borderRadius: 10,
    width: '85%',
    height: 60,
    backgroundColor: 'grey',
    paddingLeft: 10,
  },
  chatsNewChatButtonText: {
    margin: 15,
    fontWeight: 600,
    fontSize: 20,
    color: '#ffffff',
    alignSelf: 'Center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    width: 140,
    height: 40,
  },
  modalBackground: {
    width: '100%',
    flex: 1,
    backgroundColor: '#00000080',
    alignSelf: 'center',
  },
  addMemberSearchView: {
    flex: 1,
    marginTop: 10,
    marginHorizontal: 10,
    backgroundColor: 'transparent',
  },
  contactInfoName: {
    color: '#ffffff',
    margin: 15,
    marginTop: 10,
    fontSize: 24,
    fontWeight: 600,
  },
  contactInfoEmail: {
    color: '#ffffff',
    margin: 15,
    marginTop: 2,
    fontSize: 18,
    fontWeight: 600,
  },
  contactInfoUserID: {
    color: '#ffffff',
    margin: 15,
    marginTop: 2,
    fontSize: 15,
    fontWeight: 600,
  },
  contactBox: {
    flex: 1,
    flexDirection: 'row',
    borderColor: '#ffffff',
    borderWidth: 2,
    margin: 2,
  },
  contactInfoBox: {
    flex: 8,
    marginLeft: 10,
    alignSelf: 'flex-start',
  },
  contactsSearchView: {
    flex: 1,
    marginTop: 10,
    marginHorizontal: 10,
    backgroundColor: 'transparent',
    flexDirection: 'row',
  },
  contactsModalViewButtons: {
    height: '100%',
    width: '100%',
  },
  contactsModalViewButtonsText: {
    fontSize: 20,
    color: '#ffffff',
    alignSelf: 'center',
    fontWeight: 600,
    margin: 15,
  },
  sendMessageButtonText: {
    color: '#ffffff',
    margin: 8,
    fontSize: 22,
    fontWeight: 600,
  },
  sendMessageButton: {
    flex: 3,
    width: 20,
    height: '60%',
    marginRight: 10,
    bottom: '0%',
    borderRadius: 15,
    borderColor: '#ffffff',
    borderWidth: 2,
    marginTop: 15,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  sendMessageTextInput: {
    flex: 8,
    placeholderTextColor: '#ffffff',
    width: 240,
    height: '60%',
    color: '#ffffff',
    margin: 15,
    fontSize: 22,
    fontWeight: 600,
    bottom: '20%',
    paddingTop: 2,
    borderRadius: 15,
    borderColor: '#ffffff',
    borderWidth: 2,
    paddingLeft: 12,
    backgroundColor: 'gray',
  },
  sendMessageView: {
    flex: 1,
    justifyContent: 'flex-end',
    flexDirection: 'row',
    backgroundColor: '#2A2F4F',
    marginTop: 2,
  },
  messageMessage: {
    color: '#000000',
    margin: 15,
    marginTop: 10,
    marginLeft: 10,
    fontSize: 20,
    alignItems: 'center',
    fontWeight: 600,
  },
  messageTimestamp: {
    color: '#000000',
    margin: 15,
    flex: 7,
    marginTop: 2,
    marginLeft: 10,
    fontSize: 15,
    alignSelf: 'flex-start',
    fontWeight: 600,
  },
  messageAuthor: {
    color: '#000000',
    margin: 15,
    fontWeight: 600,
    flex: 3,
    marginTop: 2,
    marginLeft: 10,
    fontSize: 15,
    alignSelf: 'flex-end',
  },
  userMessageView: {
    flex: 11,
    flexDirection: 'column',
    borderColor: '#000000',
    borderTopLeftRadius: 15,
    borderBottomLeftRadius: 15,
    borderWidth: 2,
    margin: 2,
    backgroundColor: '#E5BEEC',
  },
  replyMessageView: {
    flex: 11,
    flexDirection: 'column',
    borderColor: '#000000',
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
    borderWidth: 2,
    margin: 2,
    backgroundColor: '#917FB3',
  },
  chatOptionsButton: {
    flex: 3,
    height: 50,
    width: 40,
    aspectRatio: 0.2,
    alignSelf: 'center',
  },
  chatChatName: {
    margin: 15,
    fontSize: 28,
    fontWeight: 600,
    flex: 8,
    color: '#ffffff',
    alignSelf: 'flex-start',
  },
  chatChatNameView: {
    flex: 1,
    marginLeft: 55,
    marginRight: 15,
    flexDirection: 'row',
  },
  chatChatCreator: {
    fontSize: 20,
    color: '#ffffff',
    flex: 7,
    margin: 15,
    fontWeight: 600,
  },
  modalButtonText: {
    fontWeight: 600,
    fontSize: 20,
    color: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 4,
    width: '100%',
    height: '90%',
  },
  modalOpacity: {
    width: '100%',
    flex: 1,
    backgroundColor: '#00000080',
    alignSelf: 'center',
  },
  modalTextInput: {
    color: '#ffffff',
    alignSelf: 'center',
    placeholderTextColor: '#ffffff',
    borderRadius: 10,
    backgroundColor: 'gray',
    paddingLeft: 10,
    fontWeight: 600,
    fontSize: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    width: '90%',
    height: '20%',
    marginTop: '5%',
  },
  modalTouchableHighlight2Button: {
    height: '28%',
    width: '80%',
    top: '36%',
    right: '10%',
    borderRadius: 15,
    position: 'absolute',
  },
  modalTouchableHighlight3Button: {
    height: '38%',
    width: '80%',
    top: '31%',
    right: '10%',
    borderRadius: 15,
    position: 'absolute',
  },
  modalTouchableHighlight4Button: {
    height: '44%',
    width: '80%',
    top: '28%',
    right: '10%',
    borderRadius: 15,
    position: 'absolute',
  },
  modalTouchableHighlight5Button: {
    height: '50%',
    width: '80%',
    top: '25%',
    right: '10%',
    borderRadius: 15,
    position: 'absolute',
  },
  modalViewButtons: {
    height: '100%',
    width: '100%',
    borderRadius: 15,
    position: 'absolute',
    backgroundColor: '#1f1f1f',
  },
  modalYesNoButton: {
    alignSelf: 'center',
    width: '20%',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    marginLeft: '20%',
  },
  modal3Button: {
    marginTop: '10%',
    height: '18%',
    alignSelf: 'center',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    width: '80%',
    textAlignVertical: 'center',
  },
  modal3ButtonCancel: {
    marginTop: '10%',
    height: '18%',
    alignSelf: 'center',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    width: '40%',
    textAlignVertical: 'center',
  },
  modal4Button: {
    marginTop: '7%',
    height: '16%',
    alignSelf: 'center',
    width: '80%',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    textAlignVertical: 'center',
  },
  modal4ButtonCancel: {
    marginTop: '7%',
    height: '16%',
    alignSelf: 'center',
    width: '40%',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    textAlignVertical: 'center',
  },
  modal5Button: {
    marginTop: '6%',
    height: '14%',
    alignSelf: 'center',
    width: '80%',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    textAlignVertical: 'center',
  },
  modal5ButtonCancel: {
    marginTop: '6%',
    height: '14%',
    alignSelf: 'center',
    width: '40%',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    textAlignVertical: 'center',
  },
  modal2Button: {
    marginTop: '12%',
    height: '24%',
    alignSelf: 'center',
    width: '80%',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    textAlignVertical: 'center',
  },
  modal2ButtonCancel: {
    marginTop: '12%',
    height: '24%',
    alignSelf: 'center',
    width: '40%',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
    textAlignVertical: 'center',
  },
  chatinfoMemberInfoBox: {
    flex: 8,
    marginLeft: 10,
    alignSelf: 'flex-start',
  },
  chatinfoMemberView: {
    flex: 1,
    flexDirection: 'row',
    borderColor: '#ffffff',
    borderWidth: 2,
    margin: 2,
  },
});
export default styles;
